[phases.setup]
nixPkgs = ['bun']
aptPkgs = ['build-essential']

[phases.install]
cmds = ["bun install"] # changed

[phases.build]
cmds = ["bun prisma generate --no-engine && bun run build"] # changed

[start] # changed
cmd = "node /home/bun/app/.next/standalone/server.js" 